pygments: true
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks

url: http://amnesiac10.github.io

# markdown: rdiscount
permalink: /:title/
name: AutoHotkey 之美
author: amnesiac
qq: 
email: rhong.fu@gmail.com
duoshuo: amnesiac10
beian: 
cnzz: 
weibo: 1861687067
github: amnesiac10
safe: true
paginate: 15
about: "AutoHotkey 特点介绍、编写经验及使用心得等。 如果您有好文章，欢迎分享。<br /><br />如果喜欢，请分享到微博、微信等。"
