# 站点配置
highlighter: pygments
pygments: true
# 这里设置 redcarpet 作为 md 引擎为什么不会重新生成文章？即无效，这样就无法使用 fenced_code_blocks 语法来高亮代码了。但为什么 rdiscount 又能识别 `````` 中为代码却不能高亮呢？
markdown: redcarpet
redcarpet:
  extensions: [fenced_code_blocks]
  render_options:
# redcarpet:
        #  extensions: []
          #    - hard_wrap
      #    - no_intra_emphasis
      #    - autolink
      #    - strikethrough
      #    - fenced_code_blocks
safe: false
# 个人信息
qq: 
email: rhong.fu@gmail.com
uyanid: 1950228
beian: 
cnzz: 
weibo: 1861687067
github: amnesiac10

# 站点信息设置
url: http://amnesiac10.github.io
permalink: /:year/:month/:day/:title.html
author: amnesiac
paginate: 15
project: amnesiac10.github.io
name: AutoHotkey 之美
about: "AutoHotkey 特点介绍、编写经验及使用心得等。 如果您有好文章，欢迎分享。<br /><br />如果喜欢，请分享到微博、微信等。"
