# 站点配置
pygments: true
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
safe: true

# 个人信息
qq: 
email: rhong.fu@gmail.com
duoshuo: amnesiac10
beian: 
cnzz: 
weibo: 1861687067
github: amnesiac10

# 站点信息设置
url: http://amnesiac10.github.io
permalink: date
author: amnesiac
paginate: 15
project: amnesiac10.github.io
name: AutoHotkey 之美
about: "AutoHotkey 特点介绍、编写经验及使用心得等。 如果您有好文章，欢迎分享。<br /><br />如果喜欢，请分享到微博、微信等。"
